version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: redfinger-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redfinger_v4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redfinger-net
    restart: always

  redis:
    image: redis:alpine
    container_name: redfinger-redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - redfinger-net
    restart: always

volumes:
  postgres_data:
  redis_data:


networks:
  redfinger-net:
    driver: bridge
